### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gotktrix#1]
- [ ] Read check should account for `m.replaces` events.
- [x] Rooms shouldn't display preview for non-message events (including edits).
	- [ ] This should be customizable, maybe.
- [x] Implement redaction support.
- [x] Implement working hyperlinks.
